# Generated by Django 4.1.7 on 2023-02-19 14:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
